---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
     - enable_repo

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
    - haproxy
    
- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - tomcat


- name: deploy postgres
  hosts: apps
  gather_facts: false
  become: true
  hosts: appdbs

  roles:
    - postgres

